mongo:
  database: brawl
  host: 127.0.0.1:27017
  username: admin
  password: ''
version: "v1.0"
ALLOWED_COMMANDS:
  - ignore
  - unignore
  - reply
  - r
  - tell
  - msg
  - m
  - pm
  - whisper
  - w
  - togglepm
  - tpm
  - togglesounds
  - sounds
  - list
  - who
  - ping
  - reclaim
  - claim
  - report
  - request
  - helpop
TEAM:
  SIZE: 5
LANGUAGE:
  ITEM:
    ARENA:
      '0':
        TYPE: IRON_SWORD
        NAME: "&7» &d&lUnranked Queue &7«"
        META: DUEL_ARENA_UNRANKED
      '1':
        TYPE: BLAZE_ROD
        NAME: '&7» &e&lDuel Player &7«'
        META: DUEL_ARENA_DUEL
      '4':
        TYPE: REDSTONE_TORCH_ON
        NAME: '&7» &c&lSpectator Mode &7«'
        META: SPECTATE_ARENA
      '7':
        TYPE: 351
        DATA: 8
        NAME: '&7» &a&lQuick Queue &7«'
        META: DUEL_ARENA_QUICK_QUEUE
      '8':
        TYPE: 351
        DATA: 1
        NAME: '&7» &cReturn to &lSpawn &7«'
        META: DUEL_ARENA_LEAVE
    SPAWN:
      '0':
        TYPE: BOOK
        NAME: "&7\u00bb &5&lKit Selector &7\u00ab"
        META: KIT_SELECTOR
      '1':
        TYPE: IRON_SWORD
        NAME: "&7\u00bb &6&lDuel Arena &7\u00ab"
        META: DUEL_ARENA
      '4':
        TYPE: EMERALD
        NAME: "&7\u00bb &2&lShop &7\u00ab"
        META: SHOP
      '7':
        TYPE: NETHER_STAR
        NAME: "&7\u00bb &e&lEvent Selector &7\u00ab"
        META: EVENT_SELECTOR
      '8':
        TYPE: REDSTONE_COMPARATOR
        NAME: "&7\u00bb &d&lSettings &7\u00ab"
        META: SETTINGS
    GAME_LOBBY:
      LEAVE_EVENT:
        TYPE: 351
        DATA: 1
        NAME: '&7» &c&lLeave Game &7«'
        META: EVENT_LEAVE
      OPTIONS:
        TYPE: HOPPER
        DATA: 1
        NAME: '&7» &e&lGame Options &7«'
        META: EVENT_OPTIONS
      VOTE:
        TYPE: 395
        NAME: '&7» &b&l{MAP_NAME} &7«'
        META: EVENT_VOTE
      VOTE_SELECTED:
        TYPE: MAP
        NAME: '&7» &a&l{MAP_NAME} &7«'
        META: EVENT_VOTE_SELECTED
    QUEUE:
      '8':
        TYPE: 351
        DATA: 1
        NAME: '&7» &c&lLeave Queue &7«'
        META: QUEUE_LEAVE
    SPECTATOR:
      '0':
        TYPE: COMPASS
        NAME: '&7» &5&lSpectate Player &7«'
        META: SPECTATOR_PLAYER_MENU
      '3':
        TYPE: NETHER_STAR
        NAME: '&7» &a&lActive Game &7«'
        META: SPECTATE_GAME
      '4':
        TYPE: WATCH
        NAME: '&7» &e&lSpawn &7«'
        META: SPECTATE_SPAWN
      '5':
        TYPE: 381
        NAME: '&7» &6&l1v1 &7«'
        META: SPECTATE_ARENA
      '8':
        TYPE: 351
        DATA: 1
        NAME: '&7» &c&lLeave Spectator &7«'
        META: SPECTATOR_LEAVE
LOCATIONS:
  SPAWN:
    world: world
    x: 0.5
    y: 100.0
    z: 0.5
    yaw: 0.09051448
    pitch: -0.24124241
  HOLO_LB:
    world: world
    x: -6.492060429424009
    y: 99.5
    z: -6.42366813868594
    yaw: -42.414062
    pitch: 3.3235397
  HOLO_STATS:
    world: world
    x: 7.377283159491882
    y: 99.5
    z: -6.427592770642988
    yaw: -310.97046
    pitch: -0.894106
  GAME_LOBBY:
    world: world
    x: 0.6615065722248856
    y: 121.0
    z: 170.36529824108345
    yaw: -180.49551
    pitch: -3.164398
  DUEL_ARENA:
    world: world
    x: 1000.6690045937258
    y: 100.0
    z: 1000.155723071546
    yaw: -0.6047363
    pitch: 0.94663006